### PR TITLE
Revert "Added PhonelabSource processor and generator"

### PR DESCRIPTION
**Pull request by shaseley**
Reverts shaseley/phonelab-go#1

### CODE REVIEW

**Comment by gurupras** [comment]
What's wrong?

**Comment by shaseley** [comment]
"github.com/gurupras/phonelab-go/hdfs"

This path doesn't get changed so this is a bad import.

**Comment by gurupras** [comment]
Good point. How do we handle sub packages?

**Comment by shaseley** [comment]
I can change it to "github.com/shaseley/phonelab-go/hdfs"

**Comment by shaseley** [comment]
I'm not sure if subpakages can be handled through pull requests or not...

**Comment by gurupras** [comment]
Should this be a submodule/separate git repo?
Is that the right way to handle stuff like this?

I feel like any future merge is also going to suffer from the same problem unless i delete my repo and work off of yours

**Comment by shaseley** [comment]
For now, I'll just change the import and push. Future merges will def. suffer working this way if you add any subpackages , including new binaries.

**Comment by gurupras** [comment]
For future reference, apaprently, the right way to handle this is listed here:
http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

**Pull request closed without merging**
